# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_auto_20161220_0006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-published", "-created")},
        ),
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(max_length=500),
        ),
    ]
